version: '3.7'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # NestJS Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: sh -c "npm run typeorm:run && npm run start:prod"

volumes:
  pg_data: